### ISSUE TITLE
Heroku Error 500

### ISSUE THREAD

**Issue by tufail** [Jam3/nextjs-boilerplate#100]
`2021-05-02T15:40:40.962546+00:00 heroku[router]: at=info method=GET path="/_next/static/84mVc0CQI-Fv9LtAUe9bm/_buildManifest.js" host=main-dash.herokuapp.com request_id=ba91f661-642a-4032-897e-af906d02c4a3 fwd="122.167.162.95" dyno=web.1 connect=1ms service=9ms status=200 bytes=963 protocol=https`

Please help me , I am trying to deploy on Heroku but getting the above 500 error

**Comment by iranreyes** [comment]
Hi @tufail,

I need more details to help you. 
Based on the example log you added, it seems that the file is returning 200. Therefore I don't know where the 500 error comes from. 

As a note, this boilerplate creates a static site located in `./out`that should be deployed. Based on the nature that everything is static, and there is no back-end or infrastructure, the source of the 500 error shouldn't be on this boilerplate.

Greetings,
Iran
