### ISSUE TITLE
[Feature] Make generator a deployable npm package 

### ISSUE THREAD

**Issue by iranreyes** [Jam3/nextjs-boilerplate#11]
**Is your feature request related to a problem? Please describe.**
Currently, it's a project boilerplate and can not be published to npm

**Describe the solution you'd like**
Wrap the generator in `nyg` like the previous version.

**Describe alternatives you've considered**
N/A

**Comment by neo** [comment]
https://github.com/Rich-Harris/degit

**Comment by iranreyes** [comment]
Two solutions so far:
1. Integrate nyg here and move things around.
2. Create a separate npm package that clones this repo (it's more clean)

**Comment by neo** [comment]
Another way I like is with GitHub template b/c we'd have to create a repo on GitHub for every new project anyway; so it would be very convenient.
And it's an opt-in thing, we could mark this as an template and still combine/integrate with other solutions.

**Comment by jmckinnell** [comment]
Do we want to close this? We're using this as a Github template currently.
