### ISSUE TITLE
[Feature] CookieBanner component / handler

### ISSUE THREAD

**Issue by DonghyukJacobJang** [Jam3/nextjs-boilerplate#112]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**What does the proposed API look like?**
What kind of methods it will have, how do you think you will use it?

**Additional context**

**Comment by DonghyukJacobJang** [comment]
Neo posted: https://github.com/bring-shrubbery/use-cookie-consent

**Comment by jmckinnell** [comment]
This has been completed and merged into main.
