### ISSUE TITLE
[Bug] Linter Issue - @next/next/no-document-import-in-page

### ISSUE THREAD

**Issue by grez96** [Jam3/nextjs-boilerplate#145]
`npm run linters`

generates the following error:
![image](https://user-images.githubusercontent.com/42558504/134540507-b16f6383-9ce7-466a-83c5-dc514eb8e739.png)
`Error: next/document should not be imported outside of pages/_document.js. See https://nextjs.org/docs/messages/no-document-import-in-page.`

Seems to happen because nextjs expects `_document` file to end with a `.js` extension, but in reality it ends with a `.tsx` extension

**Comment by DonghyukJacobJang** [comment]
https://github.com/vercel/next.js/issues/28596

**Comment by AaronLayton** [comment]
Just dropping a note to say still an issue and replicable with `"eslint-config-next": "^11.1.2",` on Windows

Temporarily adding the ignore line

```json
{
  "extends": ["next", "next/core-web-vitals"],
  "rules": {
    "@next/next/no-document-import-in-page": "off"
  }
}
```
