### ISSUE TITLE
[Bug] Map files in the production static build

### ISSUE THREAD

**Issue by iranreyes** [Jam3/nextjs-boilerplate#16]
## Describe the bug

After running a production build, some of the build files in the _next folder have map files.

## To Reproduce

1. Run `npm run build:prod:static`
2. Go to `out/_next/static/chunks`

You will find some *.map files.

## Screenshots

![image](https://user-images.githubusercontent.com/5953115/76168405-ec1a3680-6145-11ea-9c2a-b088e50b1dbd.png)

## Expected behaviour

Source maps should be available in every environment except production.

**Comment by DonghyukJacobJang** [comment]
Reference : 
https://github.com/zeit/next-plugins/tree/master/packages/next-source-maps

**Comment by DonghyukJacobJang** [comment]
#88

**Comment by DonghyukJacobJang** [comment]
This issue has resolved by merging PR #88 .
