### ISSUE TITLE
Need to update lint-staged to use `next lint`

### ISSUE THREAD

**Issue by neo** [Jam3/nextjs-boilerplate#175]
instead of the direct use of `eslint`

**Comment by DonghyukJacobJang** [comment]
oh this is a great call.

**Comment by DonghyukJacobJang** [comment]
I was following this https://nextjs.org/docs/basic-features/eslint#lint-staged, and got an issue.

```
✖ next lint --fix --file /lint-staged.config.js --file /src/components/AppAdmin/AppAdmin.tsx:
Unknown or unexpected option: --file
```

**Comment by DonghyukJacobJang** [comment]
NextJS 12 support --file option. 
<img width="850" alt="Screen Shot 2021-11-22 at 4 04 05 PM" src="https://user-images.githubusercontent.com/16929537/142935123-f4e2fd04-4b49-4e5a-acf7-2bf14845a503.png">


https://nextjs.org/blog/next-12#other-improvements
