### ISSUE TITLE
[Feature] Replace unsupported page logic with plain unsupported.html page

### ISSUE THREAD

**Issue by namniak** [Jam3/nextjs-boilerplate#21]
**Is your feature request related to a problem? Please describe.**
When unsupported page is a part of app, there's a big chance it will break in old browsers (IE) when using modern JS syntax without using polyfills.

**Describe the solution you'd like**
We should have a standalone simple `unsupported.html` page with a full list of HEAD metatags that has isolated styles. Then we redirect to it via AWS lambda@edge (this won't be included in the source code of the project).

**Additional context**
Clean up all code related to the existing unsupported approach

**Comment by iranreyes** [comment]
Maybe we should add the lambda code in the generator, or a link to the implementation

**Comment by iranreyes** [comment]
@neo Could you point us to the nextjs native solution to handle unsupported pages?

**Comment by neo** [comment]
yes, but it would only solve half of the problem but not the serving part?

**Comment by neo** [comment]
or is the serving part in the devops repo

**Comment by namniak** [comment]
https://github.com/Jam3/nyg-nextjs/pull/64
