### ISSUE TITLE
[Feature] Update ls lint to reject file names with + included 

### ISSUE THREAD

**Issue by ameliemaia** [Jam3/nextjs-boilerplate#242]
**Is your feature request related to a problem? Please describe.**
AWS buckets don't like + in file names. It causes errors when requesting assets.

**Describe the solution you'd like**
We should update the ls lint rules to check for + in file names and throw errors if found.

**Describe alternatives you've considered**

**What does the proposed API look like?**
What kind of methods it will have, how do you think you will use it?

**Additional context**

**Comment by fzhang13** [comment]
PR opened for this to address linters, should we also include other symbols potentially as well?
