### ISSUE TITLE
[Feature] Flow integration

### ISSUE THREAD

**Issue by namniak** [Jam3/nextjs-boilerplate#25]

**Comment by namniak** [comment]
[PR](https://github.com/Jam3/nyg-nextjs/pull/26)

**Comment by amelierosser** [comment]
Once this merge is in, would it be possible to put the flow config in its own repo so we can use across multiple projects? I'd love to use the same config here: https://github.com/Jam3/intern-webgl-react-app

**Comment by DonghyukJacobJang** [comment]
@namniak @ameliemaia closing this ticket because we will likely move forward with TS instead in the near future.
