### ISSUE TITLE
[Bug] withRedux doesn't work with getStaticProps

### ISSUE THREAD

**Issue by neo** [Jam3/nextjs-boilerplate#40]
the `withRedux` wrapper which uses `getInitialProps` under the hood, isn't compatible with using `getStaticProps` because only either one or the other could be present, but not both.

**Comment by neo** [comment]
maybe this could be a potential solution?
https://github.com/kirill-konshin/next-redux-wrapper#getstaticprops

**Comment by neo** [comment]
I think they also updated their example: https://github.com/vercel/next.js/tree/canary/examples/with-redux

**Comment by neo** [comment]
now that I have actually used this, I think for ssg we should use provide the store with the initial state in `_app.js`? because most of these complicated methods are trying to solve problems for ssr, which we don't use often.

**Comment by namniak** [comment]
https://github.com/Jam3/nyg-nextjs/pull/62
