### ISSUE TITLE
[Feature] Middleware API proxy

### ISSUE THREAD

**Issue by iranreyes** [Jam3/nextjs-boilerplate#47]
**Is your feature request related to a problem? Please describe.**
Final API endpoints are password protected.

**Describe the solution you'd like**
Local middleware without protection

**Describe alternatives you've considered**
NodeJS server

**What does the proposed API look like?**
A mirror of the real API endpoints

**Additional context**
@jeff-ong had this issue in a recent project

**Comment by DonghyukJacobJang** [comment]
@iranreyes @jeff-ong NextJS has API routes feature, and it works out of box. it does not require any NodeJS server running on the side. Anyone can write their own API routes with mock data and simulate it without protection worry. We have used this feature in 2002-ComplexLand project and maybe more projects that I do not aware of. 

Here is a reference [link](https://nextjs.org/docs/api-routes/introduction)

Please feel free to close this ticket if that is what you have been looking for.

**Comment by iranreyes** [comment]
Down to close it

**Comment by DonghyukJacobJang** [comment]
Closing the issue.
