### ISSUE TITLE
[Bug] Environment Variables

### ISSUE THREAD

**Issue by grez96** [Jam3/nextjs-boilerplate#48]
https://github.com/Jam3/nyg-nextjs/pull/45

**Comment by neo** [comment]
continuing the discussion here that I have found the temporary solution to be removing. the `.env.production` file and have some custom named files instead so that nextjs won't pick that up.

**Comment by namniak** [comment]
can someone describe the issue, please?
@grez96 @neo

**Comment by neo** [comment]
@namniak sorry for the delay 😅  you would just need to rename the `.env.production` to `.env.prod` or something. The issue is that `.env.production` would apply to all build environments because it's a "production" build.
