### ISSUE TITLE
[Issue] Use absolute path on the social image meta header

### ISSUE THREAD

**Issue by iranreyes** [Jam3/nextjs-boilerplate#69]
Currently the `og:image` meta header has a relative path, however, the right implementation should be an absolute path.
![Screen Shot 2020-11-05 at 5 09 47 PM](https://user-images.githubusercontent.com/5953115/98382522-4f33d400-2019-11eb-9a99-93e2353b8d06.png)

Action Plan:
1. Make sure the path is absolute.

**Comment by DonghyukJacobJang** [comment]
#89
