### ISSUE TITLE
[Bug] Issues around using `linters` in the `pre-push` hook

### ISSUE THREAD

**Issue by jmckinnell** [Jam3/nextjs-boilerplate#8]
## Describe the bug

Step 1: Make a sick ass commit for a cool new feature.
Step 2: Try to push your awesome branch to the repo
Step 3: Have the Pre-push hook tell your code is kinda lame (i.e. sass-linter catches)
Step 4: Fix issue
Step 5: Don't commit your fix
Step 6: Push branch to repo successfully because linter is checking code on file not in commit 🙈 
Step 7: ????
Step 8: Profit! 🎈 

## Expected behaviour

We should lint on commit only because that's the only way code can make it into the repo.

## Relevant code

```
"husky": {
    "hooks": {
      "pre-commit": "echo 'Pre-commit checks...' && lint-staged",
      "pre-push": "echo 'Pre-push checks...' && npm run linters",
      "commitmsg": "commitlint -e $GIT_PARAMS"
    }
  },
```

**Comment by jmckinnell** [comment]
cc: @alemesa

**Comment by alemesa** [comment]
yeah @DonghyukJacobJang shouldn't all these checks run pre-commit or it takes too much time?
```js
"husky": {
    "hooks": {
      "pre-commit": "echo 'Pre-commit checks...' && npm run linters && lint-staged",
      "commitmsg": "commitlint -e $GIT_PARAMS"
    }
  },
```

**Comment by iranreyes** [comment]
Solution: move it to the `pre-commit`

**Comment by DonghyukJacobJang** [comment]
Not able to re-produce it anymore without changing.
