### ISSUE TITLE
[Feature] Find an alternative to node-sass

### ISSUE THREAD

**Issue by jmckinnell** [Jam3/nextjs-boilerplate#84]
Node-sass sucks and is constantly breaking in build. Is there another Sass build tool?

**Comment by neo** [comment]
I think this is the right call also because `node-sass` is being deprecated: https://sass-lang.com/blog/libsass-is-deprecated
And there *is* a straightforward recommended replacement called `sass` (not surprised at all :joy: )

**Comment by DonghyukJacobJang** [comment]
@jmckinnell @neo are we cool with closing this? our current boilerplate does not include `node-sass` package anymore.

**Comment by jmckinnell** [comment]
@DonghyukJacobJang yes of course
